In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mp
from sklearn.impute import SimpleImputer
%matplotlib inline

from sklearn.model_selection import train_test_split

In [2]:
# get the dataset
test = pd.read_csv("test.csv")
test

x          y
0    77  79.775152
1    21  23.177279
2    22  25.609262
3    20  17.857388
4    36  41.849864
..   ..        ...
295  71  68.545888
296  46  47.334876
297  55  54.090637
298  62  63.297171
299  47  52.459467

[300 rows x 2 columns]

In [3]:
#split the dataset 
x=test.iloc[:,0].values.reshape(-1,1)
y=test.iloc[:,1].values.reshape(-1,1)

In [4]:
x

array([[ 77],
       [ 21],
       [ 22],
       [ 20],
       [ 36],
       [ 15],
       [ 62],
       [ 95],
       [ 20],
       [  5],
       [  4],
       [ 19],
       [ 96],
       [ 62],
       [ 36],
       [ 15],
       [ 65],
       [ 14],
       [ 87],
       [ 69],
       [ 89],
       [ 51],
       [ 89],
       [ 27],
       [ 97],
       [ 58],
       [ 79],
       [ 21],
       [ 93],
       [ 27],
       [ 99],
       [ 31],
       [ 33],
       [ 80],
       [ 28],
       [ 47],
       [ 53],
       [ 69],
       [ 28],
       [ 33],
       [ 91],
       [ 71],
       [ 50],
       [ 76],
       [  4],
       [ 37],
       [ 70],
       [ 68],
       [ 40],
       [ 35],
       [ 94],
       [ 88],
       [ 52],
       [ 31],
       [ 59],
       [  0],
       [ 39],
       [ 64],
       [ 69],
       [ 57],
       [ 13],
       [ 72],
       [ 76],
       [ 61],
       [ 82],
       [ 18],
       [ 41],
       [ 50],
       [ 55],
       [ 13],
       [ 46],
      

In [5]:
y

array([[ 79.77515201],
       [ 23.17727887],
       [ 25.60926156],
       [ 17.85738813],
       [ 41.84986439],
       [  9.80523488],
       [ 58.87465933],
       [ 97.61793701],
       [ 18.39512747],
       [  8.74674765],
       [  2.81141583],
       [ 17.09537241],
       [ 95.14907176],
       [ 61.38800663],
       [ 40.24701716],
       [ 14.82248589],
       [ 66.95806869],
       [ 16.63507984],
       [ 90.65513736],
       [ 77.22982636],
       [ 92.11906278],
       [ 46.91387709],
       [ 89.82634442],
       [ 21.71380347],
       [ 97.41206981],
       [ 57.01631363],
       [ 78.31056542],
       [ 19.1315097 ],
       [ 93.03483388],
       [ 26.59112396],
       [ 97.55155344],
       [ 31.43524822],
       [ 35.12724777],
       [ 78.61042432],
       [ 33.07112825],
       [ 51.69967172],
       [ 53.62235225],
       [ 69.46306072],
       [ 27.42497237],
       [ 36.34644189],
       [ 95.06140858],
       [ 68.16724757],
       [ 50.96155532],
       [ 78

In [6]:
# split the data set into x train,x test, y train, y test
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state = 0)

In [7]:
x_train

array([[ 28],
       [ 63],
       [ 61],
       [  1],
       [ 19],
       [ 96],
       [ 56],
       [ 16],
       [ 89],
       [ 70],
       [ 81],
       [ 14],
       [ 72],
       [ 21],
       [ 12],
       [ 36],
       [ 69],
       [ 87],
       [ 73],
       [ 30],
       [ 13],
       [ 42],
       [ 57],
       [ 23],
       [  5],
       [ 81],
       [ 59],
       [ 39],
       [ 78],
       [ 16],
       [ 64],
       [  4],
       [ 56],
       [ 46],
       [ 94],
       [ 33],
       [ 82],
       [ 59],
       [ 97],
       [ 87],
       [ 25],
       [ 21],
       [ 78],
       [ 37],
       [ 13],
       [ 87],
       [ 31],
       [ 13],
       [ 43],
       [ 55],
       [ 63],
       [  7],
       [ 80],
       [ 48],
       [ 38],
       [ 13],
       [ 66],
       [ 19],
       [ 41],
       [ 51],
       [ 27],
       [ 99],
       [ 65],
       [ 39],
       [ 28],
       [  0],
       [ 32],
       [ 26],
       [ 46],
       [ 36],
       [ 21],
      

In [8]:
x_test

array([[ 67],
       [ 27],
       [ 96],
       [100],
       [ 28],
       [ 65],
       [ 37],
       [ 40],
       [ 52],
       [ 89],
       [ 92],
       [ 15],
       [ 37],
       [ 90],
       [ 89],
       [ 15],
       [ 55],
       [ 67],
       [ 14],
       [ 49],
       [ 92],
       [ 74],
       [ 41],
       [ 29],
       [ 48],
       [ 17],
       [ 61],
       [ 16],
       [ 65],
       [ 71],
       [ 63],
       [ 41],
       [ 20],
       [ 98],
       [  4],
       [ 60],
       [ 58],
       [ 93],
       [ 47],
       [ 15],
       [ 42],
       [ 43],
       [ 27],
       [ 28],
       [  0],
       [ 53],
       [ 56],
       [ 82],
       [ 95],
       [ 37],
       [ 53],
       [ 44],
       [ 56],
       [  1],
       [ 57],
       [ 60],
       [ 21],
       [ 79],
       [ 59],
       [ 84]], dtype=int64)

In [9]:
y_train

array([[ 29.31770045],
       [ 63.28312382],
       [ 59.225745  ],
       [  5.3136862 ],
       [ 14.99514319],
       [ 96.11982476],
       [ 61.09367762],
       [ 16.68715211],
       [ 92.11906278],
       [ 67.2352155 ],
       [ 78.79008525],
       [ 15.49301141],
       [ 77.9969477 ],
       [ 19.1315097 ],
       [ 12.11219941],
       [ 38.67780759],
       [ 69.46306072],
       [ 84.06676818],
       [ 72.86282528],
       [ 26.48713683],
       [  9.74416426],
       [ 38.98317436],
       [ 51.57326718],
       [ 23.52647153],
       [  0.67607675],
       [ 73.9308764 ],
       [ 62.22635684],
       [ 38.05766408],
       [ 81.40381769],
       [ 11.21710477],
       [ 67.68142149],
       [  5.60766487],
       [ 56.01448111],
       [ 48.35172635],
       [ 97.00148372],
       [ 30.48881287],
       [ 88.54475895],
       [ 59.61247085],
       [101.0697879 ],
       [ 90.65513736],
       [ 30.41303282],
       [ 19.87562242],
       [ 74.4993599 ],
       [ 40

In [10]:
y_test

array([[ 68.48820749],
       [ 30.49412933],
       [ 95.14907176],
       [103.5266162 ],
       [ 28.15668543],
       [ 68.94699774],
       [ 40.00709598],
       [ 48.09843134],
       [ 54.08170635],
       [ 87.45721555],
       [ 91.30863673],
       [ 14.82248589],
       [ 34.12473248],
       [ 89.899991  ],
       [ 89.82634442],
       [ 13.25690647],
       [ 55.81628509],
       [ 67.02150613],
       [ 12.42624606],
       [ 52.28620611],
       [ 89.73153611],
       [ 75.69298554],
       [ 45.44599591],
       [ 26.49487961],
       [ 47.41006725],
       [ 13.41310757],
       [ 60.07137496],
       [ 16.74923937],
       [ 66.61499643],
       [ 68.5458879 ],
       [ 58.61466887],
       [ 38.68888682],
       [ 18.39512747],
       [ 95.58017185],
       [  7.64652976],
       [ 59.8313966 ],
       [ 57.48741435],
       [ 99.43577876],
       [ 52.45946688],
       [  9.80523488],
       [ 42.03835773],
       [ 48.67252645],
       [ 23.44479161],
       [ 33

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
# from linear regression improt linear regression functions
lr=LinearRegression()

In [13]:
lr.fit(x_train,y_train)

LinearRegression()

In [14]:
# predict the value form test set
predictvalue = lr.predict(x_test)
predictvalue

array([[ 67.43480541],
       [ 26.85681758],
       [ 96.8538466 ],
       [100.91164538],
       [ 27.87126727],
       [ 65.40590602],
       [ 37.00131454],
       [ 40.04466362],
       [ 52.21805998],
       [ 89.75269872],
       [ 92.79604781],
       [ 14.68342123],
       [ 37.00131454],
       [ 90.76714842],
       [ 89.75269872],
       [ 14.68342123],
       [ 55.26140906],
       [ 67.43480541],
       [ 13.66897153],
       [ 49.17471089],
       [ 92.79604781],
       [ 74.53595329],
       [ 41.05911332],
       [ 28.88571697],
       [ 48.16026119],
       [ 16.71232062],
       [ 61.34810724],
       [ 15.69787092],
       [ 65.40590602],
       [ 71.4926042 ],
       [ 63.37700663],
       [ 41.05911332],
       [ 19.75566971],
       [ 98.88274599],
       [  3.52447457],
       [ 60.33365754],
       [ 58.30475815],
       [ 93.81049751],
       [ 47.1458115 ],
       [ 14.68342123],
       [ 42.07356302],
       [ 43.08801271],
       [ 26.85681758],
       [ 27

In [15]:
compare = pd.DataFrame(x_test,columns=['x'])

In [16]:
# compare the avaliable value and predict value
compare["AVLDATA"]=y_test
compare['Predictdata']=predictvalue
compare

x     AVLDATA  Predictdata
0    67   68.488207    67.434805
1    27   30.494129    26.856818
2    96   95.149072    96.853847
3   100  103.526616   100.911645
4    28   28.156685    27.871267
5    65   68.946998    65.405906
6    37   40.007096    37.001315
7    40   48.098431    40.044664
8    52   54.081706    52.218060
9    89   87.457216    89.752699
10   92   91.308637    92.796048
11   15   14.822486    14.683421
12   37   34.124732    37.001315
13   90   89.899991    90.767148
14   89   89.826344    89.752699
15   15   13.256906    14.683421
16   55   55.816285    55.261409
17   67   67.021506    67.434805
18   14   12.426246    13.668972
19   49   52.286206    49.174711
20   92   89.731536    92.796048
21   74   75.692986    74.535953
22   41   45.445996    41.059113
23   29   26.494880    28.885717
24   48   47.410067    48.160261
25   17   13.413108    16.712321
26   61   60.071375    61.348107
27   16   16.749239    15.697871
28   65   66.614996    65.405906
29   71   68.545888    71.492604
30   63   58.614669    63.377007
31   41   38.688887    41.059113
32   20   18.395127    19.755670
33   98   95.580172    98.882746
34    4    7.646530     3.524475
35   60   59.831397    60.333658
36   58   57.487414    58.304758
37   93   99.435779    93.810498
38   47   52.459467    47.145811
39   15    9.805235    14.683421
40   42   42.038358    42.073563
41   43   48.672526    43.088013
42   27   23.444792    26.856818
43   28   33.071128    27.871267
44    0   -1.040114    -0.533324
45   53   60.207583    53.232510
46   56   57.191035    56.275859
47   82   85.455042    82.651551
48   95   97.617937    95.839397
49   37   36.113348    37.001315
50   53   50.170086    53.232510
51   44   45.963969    44.102462
52   56   54.554470    56.275859
53    1    0.275307     0.481125
54   57   56.148341    57.290308
55   60   60.111350    60.333658
56   21   18.983223    20.770119
57   79   78.310565    79.608202
58   59   60.917927    59.319208
59   84   85.186573    84.680450

In [17]:
#from sk learn inport mean squared , mean absolure error and r2 score
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [18]:
mean_squared_error(y_test,predictvalue)

8.388794074847828

In [19]:
mean_absolute_error(y_test,predictvalue)

2.2723148666042317

In [20]:
r2_score(y_test,predictvalue)

0.9889794732637583